version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres.pivijyhzrwjisemlrlfz:tuyishimeKyrie%40123@aws-0-ca-central-1.pooler.supabase.com:6543/postgres
    ports:
      - "8080:8080"
